### PR TITLE
Migrated to tauri v2

### PR DESCRIPTION
**Pull request by LucFauvel**

### CODE REVIEW

**Comment by Hacksore** [comment]
actually goated @LucFauvel. This is probably worth landing on `main` and we vibe with it on canary.

Will merge after I do a bit moar testing.

**Comment by LucFauvel** [comment]
@Hacksore Only thing I don't know if it works properly is updater. Rest I tested and work well on windows.

**Comment by Hacksore** [comment]
@LucFauvel I found one thing we regressed with the window state plug-in fixing it now.
https://github.com/tauri-apps/plugins-workspace/issues/1546 / https://github.com/overlayeddev/overlayed/commit/f3359fdcf24d5d73b1f4f66f988b4c9b7d0c09e9

I'll see if I can figure out how to test the autoupdater too.

**Comment by Hacksore** [comment]
Yeah the updater is cooked, let me read the docs.
image

**Comment by Hacksore** [comment]
@LucFauvel I think we're so back and to test the updater you just make your local version in `tauri.conf.json` lower than what's released.

https://github.com/user-attachments/assets/dcbf7eb0-c6e3-4e93-92b5-4a6751bd2e25

**Comment by LucFauvel** [comment]
@Hacksore yeah I just realized I changed the condition so its always displaying updating kek

**Pull request merged**
