### PR TITLE
feat: implement set_inactive_on_mouse_hover

### PR DESCRIPTION
**Pull request by ahkohd**
This pull request implements a new feature for Overlayed. When pinned, on mouse hover, it hides and allows the user to click through!

https://github.com/user-attachments/assets/a21b76ef-8c0f-4787-ae46-d18a901a948e

### CODE REVIEW

**Comment by Hacksore** [comment]
@ahkohd This is a fantastic PR and if someone wants they can add opacity later to address #170.

Found a bug with this when you attempt to use the menubar to unpin.

https://github.com/user-attachments/assets/c04983ee-48b0-4e4f-af42-80de0475d8a9

**Comment by ahkohd** [comment]
> @ahkohd This is a fantastic PR and if someone wants they can add opacity later to address #170.
> 
> Found a bug with this when you attempt to use the menubar to unpin.
> 
>  2024-07-20_12-54-43.mp4

Okay will fix.

**Comment by ahkohd** [comment]
Fixed, please refer to commit a14418e

https://github.com/user-attachments/assets/b8edf680-fb9e-4a64-8b83-20bcb011de37

**Comment by Hacksore** [comment]
@ahkohd Tried latest code from this PR and it crashes on windows.

No helpful stack trace either on the terminal when running in release mode:

https://github.com/user-attachments/assets/b2a9cd78-4f36-4e26-95a4-78447a31e9fb


dev mode:
```
PS C:\Users\seanb\Documents\code\overlayed\apps\desktop\src-tauri> $env:RUST_BACKTRACE="full"
PS C:\Users\seanb\Documents\code\overlayed\apps\desktop\src-tauri> pnpm tauri dev            

> desktop@0.0.0 tauri C:\Users\seanb\Documents\code\overlayed\apps\desktop
> tauri "dev"

     Running BeforeDevCommand (`pnpm dev`)

> desktop@0.0.0 dev C:\Users\seanb\Documents\code\overlayed\apps\desktop
> vite

[sentry-vite-plugin] Warning: No auth token provided. Will not create release. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[sentry-vite-plugin] Warning: No auth token provided. Will not upload source maps. Please set the `authToken` option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
[sentry-vite-plugin] Info: Sending error and performance telemetry data to Sentry. To disable telemetry, set `options.telemetry` to `false`.

  VITE v5.2.13  ready in 1922 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching C:\Users\seanb\Documents\code\overlayed\apps\desktop\src-tauri for changes...
   Compiling overlayed v0.0.0 (C:\Users\seanb\Documents\code\overlayed\apps\desktop\src-tauri)
warning: constant `HIGHER_LEVEL_THAN_LEAGUE` is never used  
  --> src\constants.rs:19:11
   |
19 | pub const HIGHER_LEVEL_THAN_LEAGUE: i32 = 1001;
   |           ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `overlayed` (bin "overlayed") generated 1 warning  
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.49s
 ELIFECYCLE  Command failed with exit code 3221225477.
```

**Comment by Hacksore** [comment]
Since this will grow of merge conflicts and the windows versions was super bugged let's revisit another time.

Thanks for the work though!

**Comment by ahkohd** [comment]
okay, cool

**Pull request closed without merging**
