### PR TITLE
feat: OS-Aware Card

### PR DESCRIPTION
**Pull request by Pyr33x**
I'm struggling to contribute straight to the #188 and got no way to push changes through the pr, so I had to create a new pull request.

### CODE REVIEW

**Comment by Pyr33x** [comment]
@Hacksore checkout if is it okay on iOS

**Comment by Hacksore** [comment]
iOS 😭
IMG_2569

**Comment by Pyr33x** [comment]
> iOS 😭

Only the platform support button will be rendered on mobile devices, is there anything that I have to add then?

**Comment by Hacksore** [comment]
see https://github.com/overlayeddev/overlayed/issues/163#issuecomment-2325407163

**Pull request closed without merging**
