### PR TITLE
Added os aware download card

### PR DESCRIPTION
**Pull request by MUK-Dev**

### CODE REVIEW

**Comment by MUK-Dev** [comment]
this commit resolves #163

**Comment by Pyr33x** [comment]
You need to format the code you've written using `pnpm format`. Also, the build was unsuccessful.

**Comment by MUK-Dev** [comment]
Formatting was the issue. It seems.

**Comment by Pyr33x** [comment]
Yes, and I want @Hacksore to wait a bit more time to close the pr, cause I'm currently working on the download ui

**Comment by Hacksore** [comment]
@MUK-Dev currently the preview env shows Linux on iOS
IMG_2553

looks like spacedrvie does a fallback on unsupported devices.
IMG_2554

**Comment by Pyr33x** [comment]
> @MUK-Dev currently the preview env shows Linux on iOS

It's same on Android tho

**Comment by MUK-Dev** [comment]
Ok, I'll take a look

**Comment by MUK-Dev** [comment]
Hi, kindly test it again. I only have a windows and android machine so I can't check on others.
`react-device-detect` doesn't detect linux so I had to check for devices manually.

**Comment by Hacksore** [comment]
see https://github.com/overlayeddev/overlayed/issues/163#issuecomment-2325407163

**Pull request closed without merging**
